# General #####################################################################
element_list:
    - Cd
    - Te

degree: 2

output_directory: "./KAs"

verbose: 2

random_seed: 1234

progress_bars: True

# Preprocess ##################################################################
experiment_path: "/blue/hennig/jasongibson/MLDB/KAs/rundir/garun_1_18_2021_7_18_51/temp/"

filename_pattern: "vasprun*"

cache_data: True

data_filename: "data.db"

max_samples_per_file: 100

min_diff: 1e-3

analyze_pair_distribution: True

analyze_fraction: 1.0

vasp_pressure: True

# Featurization ###############################################################
read_knots: False

write_knots: True

knots_file: "knots.json"

r_min_map:  # angstroms
    K-K: 1.0
    As-K: 1.0
    As-As: 1.0

r_max_map:  # angstroms
    As-As: 5.0
    As-K: 5.5
    K-K: 6.0
resolution_map:  # number of unique knots
    K-K: 25
    As-K: 25
    As-As: 25

n_jobs: 16

parallel: "python"

cache_features: True

features_filename: "features.db"

knot_spacing: "linear"


# Learning ####################################################################
frac_train: 0.5

kappa: 0.99

regularization_params:
    ridge_1b: 1e-3
    ridge_2b: 1e-8
    curve_2b: 1e-8

zero_tail: True

fit_self_energy: True

cache_features: True

features_filename: "features.db"

model_filename: "model.json"

training_filename: "training.txt"

# Postprocess #################################################################
core_correction: 1.1

plot_fit: True

plot_2B: True
