name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy


    # Pip-only installs
  - pip:
      - sphinx-autoapi
      - pymatgen
      - dscribe
      - ase
      - scikit-learn
      - onnxruntime
