name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy
  - pymatgen
  - dscribe
  - ase
  - scikit-learn
  - onnxruntime

    # Pip-only installs
  - pip:
      - sphinx-autoapi

